image = "/capstor/store/cscs/ethz/large-sc/environment/ngc_pt_jan.sqsh"

mounts = ["/capstor", "/iopsstor", "/users"]

workdir = "/iopsstor/scratch/cscs/bkundu/lsai-merger/LSAI-Checkpointing"

writable = true

[annotations]
com.hooks.aws_ofi_nccl.enabled = "true"
com.hooks.aws_ofi_nccl.variant = "cuda12"
